apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mcrusprofile
    serviceMonitorSelector: prometheus
  name: mcrusprofile
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      path: /management/prometheus
      port: http    # port name cua SVC
  namespaceSelector:
  #  any: true
     matchNames:
     - iface-uat  
  selector:
    matchLabels:
      app: mcrusprofile