apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mcrusprofile
    serviceMonitorSelector: prometheus
  name: mcrusprofile
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      path: /management/prometheus
      targetPort: 8082
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: mcrusprofile